"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import os.path

from apaf import build

APP = [os.path.join('apaf', 'run.py')]

DATA_FILES = ['contrib']

OPTIONS_PY2APP = dict(
    argv_emulation = True,
#    modules=['_psutil_osx'],
)

OPTIONS_PY2EXE = dict(
    packages = 'twisted.web'
)


setup(
    app=APP,
    data_files=DATA_FILES,
    options=dict(py2app=OPTIONS_PY2APP,
                 py2exe=OPTIONS_PY2EXE,
    ),
)
